import { useState, useRef } from "react";
import { useMutation } from "@/lib/convex";
import { api } from "@convex/_generated/api";
import { authClient } from "@/lib/auth-client";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Sparkles,
  Loader2,
  Send,
  MailOpen,
  RefreshCw,
} from "lucide-react";

interface ComposeAiEmailModalProps {
  open: boolean;
  onClose: () => void;
  lead: {
    _id: string;
    name: string;
    email: string;
  } | null;
}

const SCENARIOS = [
  {
    value: "appointment_reminder",
    label: "📅 Appointment Reminder",
    description: "Remind patient of upcoming appointment",
  },
  {
    value: "post_discharge_checkin",
    label: "🏥 Post-Discharge Check-in",
    description: "Follow up after hospital discharge",
  },
  {
    value: "billing_reminder",
    label: "💳 Billing & Payment Reminder",
    description: "Invoice and payment notice",
  },
  {
    value: "lab_results_ready",
    label: "🧬 Lab Results Ready",
    description: "Notify patient that results are available",
  },
  {
    value: "medication_reminder",
    label: "💊 Medication Reminder",
    description: "Remind patient to take medication",
  },
  {
    value: "general_outreach",
    label: "💬 General Clinical Outreach",
    description: "Custom clinical communication",
  },
];

const TONES = [
  { value: "empathetic", label: "💙 Empathetic & Warm" },
  { value: "professional", label: "🏢 Professional & Clinical" },
  { value: "urgent", label: "🚨 Urgent & Direct" },
  { value: "friendly", label: "😊 Friendly & Reassuring" },
];

export default function ComposeAiEmailModal({
  open,
  onClose,
  lead,
}: ComposeAiEmailModalProps) {
  const { data: session } = authClient.useSession();
  const logComm = useMutation(api.crm.logCommunication);

  const [scenario, setScenario] = useState("appointment_reminder");
  const [tone, setTone] = useState("professional");
  const [context, setContext] = useState("");
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [generating, setGenerating] = useState(false);
  const [sending, setSending] = useState(false);
  const [generated, setGenerated] = useState(false);

  const handleGenerate = async () => {
    if (!lead) return;
    setGenerating(true);
    setGenerated(false);

    const scenarioLabel =
      SCENARIOS.find((s) => s.value === scenario)?.label ?? scenario;
    const toneLabel = TONES.find((t) => t.value === tone)?.label ?? tone;

    const prompt = `You are a compassionate hospital communications assistant writing a professional medical email.

PATIENT: ${lead.name}
PATIENT EMAIL: ${lead.email}
SCENARIO: ${scenarioLabel}
TONE: ${toneLabel}
${context ? `ADDITIONAL CONTEXT FROM STAFF: ${context}` : ""}

Write a healthcare email with these rules:
1. Start with a warm, professional greeting using the patient's first name.
2. The email must be relevant ONLY to the selected scenario: ${scenarioLabel}.
3. Use ${toneLabel} language throughout.
4. Be concise (150-250 words max).
5. End with a professional sign-off from "MedFlow Healthcare Team".
6. Do NOT include disclaimers about being an AI.

Return ONLY valid JSON with these two fields, nothing else:
{
  "subject": "email subject line here",
  "body": "full email body text here (use \\n for line breaks)"
}`;

    try {
      // Use puter.ai client-side (no API key needed)
      const puter = (window as any).puter;
      if (!puter) {
        throw new Error(
          "Puter.js not loaded. Please refresh the page and try again.",
        );
      }

      const response = await puter.ai.chat(prompt, {
        model: "gpt-4o-mini",
      });

      const text =
        typeof response === "string"
          ? response
          : response?.message?.content ??
            response?.text ??
            JSON.stringify(response);

      // Extract JSON from response
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (!jsonMatch) throw new Error("AI did not return valid JSON.");
      const parsed = JSON.parse(jsonMatch[0]);

      setSubject(parsed.subject || "");
      setBody(parsed.body || "");
      setGenerated(true);
      toast.success("Email generated by Puter AI ✨");
    } catch (err: any) {
      console.error("Puter AI error:", err);
      toast.error(err.message || "Failed to generate email. Try again.");
    } finally {
      setGenerating(false);
    }
  };

  const handleSend = async () => {
    if (!lead || !subject || !body) {
      toast.error("Please generate an email first.");
      return;
    }
    setSending(true);
    try {
      await logComm.mutate({
        leadId: lead._id,
        subject,
        body,
        type: "email",
        aiGenerated: generated,
        tone,
        senderId: session?.user?.id ?? "unknown",
        senderName: session?.user?.name ?? "Staff",
        recipientEmail: lead.email,
      });
      toast.success(`Email logged & sent to ${lead.name} ✉️`);
      onClose();
      resetForm();
    } catch (err: any) {
      toast.error(err.message || "Failed to send email.");
    } finally {
      setSending(false);
    }
  };

  const resetForm = () => {
    setScenario("appointment_reminder");
    setTone("professional");
    setContext("");
    setSubject("");
    setBody("");
    setGenerated(false);
  };

  return (
    <Dialog open={open} onOpenChange={(o) => { if (!o) { onClose(); resetForm(); } }}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <MailOpen className="h-5 w-5 text-primary" />
            Compose AI Email
          </DialogTitle>
          <DialogDescription>
            {lead
              ? `Drafting email to ${lead.name} (${lead.email})`
              : "Select a patient to compose an email"}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-5 mt-2">
          {/* Scenario */}
          <div className="space-y-2">
            <Label className="text-sm font-semibold">Communication Scenario</Label>
            <Select value={scenario} onValueChange={setScenario}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {SCENARIOS.map((s) => (
                  <SelectItem key={s.value} value={s.value}>
                    <div>
                      <div className="font-medium">{s.label}</div>
                      <div className="text-xs text-muted-foreground">{s.description}</div>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Tone */}
          <div className="space-y-2">
            <Label className="text-sm font-semibold">Email Tone</Label>
            <Select value={tone} onValueChange={setTone}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {TONES.map((t) => (
                  <SelectItem key={t.value} value={t.value}>
                    {t.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Additional context */}
          <div className="space-y-2">
            <Label className="text-sm font-semibold">
              Additional Context <span className="font-normal text-muted-foreground">(optional)</span>
            </Label>
            <textarea
              value={context}
              onChange={(e) => setContext(e.target.value)}
              placeholder="E.g. patient is coming in for knee surgery on Monday, remind them to fast from midnight..."
              className="w-full h-20 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring resize-none"
            />
          </div>

          {/* Generate Button */}
          <Button
            onClick={handleGenerate}
            disabled={generating || !lead}
            className="w-full gap-2 bg-gradient-to-r from-violet-600 to-blue-600 hover:from-violet-700 hover:to-blue-700 text-white"
          >
            {generating ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating with Puter AI...
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" />
                {generated ? "Regenerate with Puter AI" : "Generate with Puter AI"}
              </>
            )}
          </Button>

          {/* Generated Output */}
          {(subject || body) && (
            <div className="space-y-3 border border-primary/30 rounded-lg p-4 bg-primary/5">
              <div className="flex items-center justify-between">
                <Label className="text-sm font-semibold text-primary">
                  {generated ? "✨ AI-Generated Email" : "Email Draft"}
                </Label>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => { setSubject(""); setBody(""); setGenerated(false); }}
                  className="h-7 text-xs gap-1"
                >
                  <RefreshCw className="h-3 w-3" /> Clear
                </Button>
              </div>

              <div className="space-y-2">
                <Label className="text-xs text-muted-foreground">Subject</Label>
                <Input
                  value={subject}
                  onChange={(e) => setSubject(e.target.value)}
                  className="font-medium"
                />
              </div>

              <div className="space-y-2">
                <Label className="text-xs text-muted-foreground">Body</Label>
                <textarea
                  value={body}
                  onChange={(e) => setBody(e.target.value)}
                  className="w-full h-48 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring resize-none"
                />
              </div>

              <Button
                onClick={handleSend}
                disabled={sending}
                className="w-full gap-2"
              >
                {sending ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Send className="h-4 w-4" />
                )}
                {sending ? "Sending..." : `Send to ${lead?.name}`}
              </Button>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
